<?php
$qlist = array(
        'recipient'=>array(
            		0 =>array(
                        'qid' => '0',
        	            'titleid'=>'1',
        	            'ques'=>'以下图片表示什么＿＿＿＿',
        	            'ptime'=>'50',
        	            'type'  =>'2',
        	            'pic_serial' =>'0',
        	            'fill_num'=> '4',
        	            'answer'=>'1234', 
        	            'sellist'=>array(
                            '1' =>'一',
                            '2' =>'清',
                            '3' =>'二',
                            '4' =>'白',
                            '5' =>'三',
                            '6' =>'四',
                            '7' =>'五',
                            '8' =>'六',
        	            )
        	        ),
                    1 =>array(
                        'qid' => '0',
                        'titleid'=>'2',
                        'ques'=>'以下图片表示什么?＿＿＿＿',
                        'ptime'=>'50',
                        'type'  =>'1',
                        'pic_serial' =>'1004',
                        'fill_num'=> '1',
                        'answer'=>'1',                                       
                        'sellist'=>array(
                            '1' =>'一心一意',
                            '2' =>'马踏飞燕',
                            '3' =>'走马观花',
                            '4' =>'不知所踪',
                        )
                    ),
                    2 =>array(
                        'qid' => '0',
                        'titleid'=>'1',
                        'ques'=>'以下图片表示什么?',
                        'ptime'=>'10',
                        'type'  =>'1',
                        'pic_serial' =>'1001',
                        'fill_num'=> '1',
                        'answer'=>'3', 
                        'sellist'=>array(
                            '1' =>'一心一意',
                            '2' =>'马踏飞燕',
                            '3' =>'走马观花',
                            '4' =>'不知所踪',
                        )
                    ),
                    3 =>array(
                        'qid' => '0',
                        'titleid'=>'2',
                        'ques'=>'以下图片表示什么?____',
                        'ptime'=>'50',
                        'type'  =>'2',
                        'pic_serial' =>'1004',
                        'fill_num'=> '4',
                        'answer'=>'1234',                                       
                        'sellist'=>array(
                            '1' =>'一',
                            '2' =>'清',
                            '3' =>'二',
                            '4' =>'白',
                            '5' =>'三',
                            '6' =>'四',
                            '7' =>'五',
                            '8' =>'六',
                        )
                    ),
        	        4 =>array(
                        'qid' => '0',
        	            'titleid'=>'5',
        	            'ques'=>'5-1等于?',
        	            'ptime'=>'14',
        	            'type'  =>'0',
        	            'pic_serial' =>'0',
        	            'fill_num'=> '1',
        	            'answer'=>'4',    	                   	            
        	            'sellist'=>array(
        	                '1' =>'1',
        	                '2' =>'2',
        	                '3' =>'3',
        	                '4' =>'4',
        	            )
        	        ),
        	        5 =>array(
                        'qid' => '0',
        	            'titleid'=>'6',
        	            'ques'=>'1+1等于?',
        	            'ptime'=>'15',
        	            'type'  =>'0',
        	            'pic_serial' =>'0',
        	            'fill_num'=> '1',
        	            'answer'=>'2', 
        	            'sellist'=>array(
        	                '1' =>'1',
        	                '2' =>'2',
        	                '3' =>'3',
        	                '4' =>'4',
        	            )
        	        ),
        	        6 =>array(
                        'qid' => '0',
        	            'titleid'=>'7',
        	            'ques'=>'二加壹等于?',
        	            'ptime'=>'14',
        	            'type'  =>'0',
        	            'pic_serial' =>'0',
        	            'fill_num'=> '1',
        	            'answer'=>'3',    	                   	            
        	            'sellist'=>array(
        	                '1' =>'一',
        	                '2' =>'二',
        	                '3' =>'三',
        	                '4' =>'四',
        	            )
        	        ),
        	        7 =>array(
                        'qid' => '0',
        	            'titleid'=>'8',
        	            'ques'=>'图中是什么字?',
        	            'ptime'=>'14',
        	            'type'  =>'0',
        	            'pic_serial' =>'1005',
        	            'fill_num'=> '1',
        	            'answer'=>'1',    	                   	            
        	            'sellist'=>array(
        	                '1' =>'数',
        	                '2' =>'二',
        	                '3' =>'三',
        	                '4' =>'四',

        	            )
        	        ),
        	        8 =>array(
                        'qid' => '0',
        	            'titleid'=>'9',
        	            'ques'=>'图中是什么?',
        	            'ptime'=>'14',
        	            'type'  =>'3',
        	            'pic_serial' =>'1041',
        	            'fill_num'=> '1',
        	            'answer'=>'1',    	                   	            
        	            'sellist'=>array(
        	                '1' =>'钢琴',
        	                '2' =>'小提琴',
        	                '3' =>'古筝',
        	                '4' =>'笛子',
        	            )
        	        ),
        	        9 =>array(
                        'qid' => '0',
        	            'titleid'=>'10',
        	            'ques'=>'图代表什么意思____?',
        	            'ptime'=>'14',
        	            'type'  =>'3',
        	            'pic_serial' =>'1080',
        	            'fill_num'=> '1',
        	            'answer'=>'1',    	                   	            
        	            'sellist'=>array(
        	                '1' =>'左顾右盼',
        	                '2' =>'故左顾右盼',
        	                '3' =>'有顾右盼',
        	                '4' =>'左顾右盼',
        	            )
        	        ),
        ),
        'challenger'=>array(
            0 =>array(
                'qid' => '0',
                'titleid'=>'1',
                'ques'=>'以下图片表示什么?',
                'ptime'=>'50',
                'type'  =>'2',
                'pic_serial' =>'1001',
                'fill_num'=> '4',
                'answer'=>'3', 
                'q_option'=>'1',
                'sellist'=>array(
                    '1' =>'一',
                    '2' =>'清',
                    '3' =>'二',
                    '4' =>'白',
                    '5' =>'三',
                    '6' =>'四',
                    '7' =>'五',
                    '8' =>'六',
                )
            ),
            1 =>array(
                'qid' => '0',
                'titleid'=>'2',
                'ques'=>'以下图片表示什么?＿＿＿＿',
                'ptime'=>'50',
                'type'  =>'4',
                'pic_serial' =>'1004',
                'fill_num'=> '1',
                'answer'=>'1', 
                'q_option'=>'1',                                      
                'sellist'=>array(
                )
            ),
            2 =>array(
                'qid' => '0',
                'titleid'=>'1',
                'ques'=>'以下图片表示什么?',
                'ptime'=>'10',
                'type'  =>'1',
                'pic_serial' =>'1001',
                'fill_num'=> '1',
                'answer'=>'3', 
                'q_option'=>'1',
                'sellist'=>array(
                    '1' =>'一心一意',
                    '2' =>'马踏飞燕',
                    '3' =>'走马观花',
                    '4' =>'不知所踪',
                )
            ),
            3 =>array(
                'qid' => '0',
                'titleid'=>'2',
                'ques'=>'以下图片表示什么?____',
                'ptime'=>'50',
                'type'  =>'2',
                'pic_serial' =>'1004',
                'fill_num'=> '4',
                'answer'=>'1234', 
                'q_option'=>'1',                                      
                'sellist'=>array(
                    '1' =>'一',
                    '2' =>'清',
                    '3' =>'二',
                    '4' =>'白',
                    '5' =>'三',
                    '6' =>'四',
                    '7' =>'五',
                    '8' =>'六',
                )
            ),
            4 =>array(
                'qid' => '0',
                'titleid'=>'5',
                'ques'=>'5-1等于?',
                'ptime'=>'14',
                'type'  =>'0',
                'pic_serial' =>'0',
                'fill_num'=> '1',
                'answer'=>'4',  
                'q_option'=>'1',                                    
                'sellist'=>array(
                    '1' =>'1',
                    '2' =>'2',
                    '3' =>'3',
                    '4' =>'4',
                )
            ),
            5 =>array(
                'qid' => '0',
                'titleid'=>'6',
                'ques'=>'1+1等于?',
                'ptime'=>'15',
                'type'  =>'0',
                'pic_serial' =>'0',
                'fill_num'=> '1',
                'answer'=>'2', 
                'q_option'=>'1',
                'sellist'=>array(
                    '1' =>'1',
                    '2' =>'2',
                    '3' =>'3',
                    '4' =>'4',
                )
            ),
            6 =>array(
                'qid' => '0',
                'titleid'=>'7',
                'ques'=>'二加壹等于?',
                'ptime'=>'14',
                'type'  =>'0',
                'pic_serial' =>'0',
                'fill_num'=> '1',
                'answer'=>'3',  
                'q_option'=>'1',                                    
                'sellist'=>array(
                    '1' =>'一',
                    '2' =>'二',
                    '3' =>'三',
                    '4' =>'四',
                )
            ),
            7 =>array(
                'qid' => '0',
                'titleid'=>'8',
                'ques'=>'图中是什么字?',
                'ptime'=>'14',
                'type'  =>'0',
                'pic_serial' =>'1005',
                'fill_num'=> '1',
                'answer'=>'1', 
                'q_option'=>'1',                                     
                'sellist'=>array(
                    '1' =>'数',
                    '2' =>'二',
                    '3' =>'三',
                    '4' =>'四',

                )
            ),
            8 =>array(
                'qid' => '0',
                'titleid'=>'9',
                'ques'=>'图中是什么?',
                'ptime'=>'14',
                'type'  =>'3',
                'pic_serial' =>'1041',
                'fill_num'=> '1',
                'answer'=>'1', 
                'q_option'=>'1',                                     
                'sellist'=>array(
                    '1' =>'钢琴',
                    '2' =>'小提琴',
                    '3' =>'古筝',
                    '4' =>'笛子',
                )
            ),
            9 =>array(
                'qid' => '0',
                'titleid'=>'10',
                'ques'=>'图代表什么意思____?',
                'ptime'=>'14',
                'type'  =>'3',
                'pic_serial' =>'1080',
                'fill_num'=> '1',
                'answer'=>'1',   
                'q_option'=>'1',                                   
                'sellist'=>array(
                    '1' =>'左顾右盼',
                    '2' =>'故左顾右盼',
                    '3' =>'有顾右盼',
                    '4' =>'左顾右盼',
                )
            ),
        ),
        'challenger_name'=>'挑战者',
        'challenger_right_number'=>'5',
        'challenger_cost_time'=>'80',
    );	            
?>
